### ISSUE TITLE
Stick with one database?

### ISSUE THREAD

**Issue by lightningRalf** [homanp/superagent#38]
Hey there, is there a possibility, to add:
https://supabase.com/blog/openai-embeddings-postgres-vector

instead of going with pinecone? So in this way we could store the embeddings also locally.

**Comment by homanp** [comment]
> Hey there, is there a possibility, to add: https://supabase.com/blog/openai-embeddings-postgres-vector
> 
> instead of going with pinecone? So in this way we could store the embeddings also locally.

Hey, yes it's possible. The only thing that needs to be remade is the retrieval process with `LangChain`. I choose `Pinecone` because of the `namespaces` feature in the retriever https://github.com/homanp/superagent/blob/main/app/lib/agents.py#L89

But I guess this could be replicated with `Prisma` and `Supabase`. 

Any PRs would be welcome here as I'm focusing on bringing in Tools atm.

**Comment by thesushilsharma** [comment]
Need to update .env.example 


Basically, a database migration variable is not required.

**Comment by homanp** [comment]
> Need to update .env.example 
> 
> 
> 
> 
> 
> Basically, a database migration variable is not required.

How would you handle the retrieval in the Agent `class` @thesushilsharma ? With Pinecone you can store all embedding sim one index and to context querying using the `namspace` identifier. How would this work with pg vector? 

If possible please do a PR containing the Prisma schema and the changes to the Agent class. 

Thanks!

**Comment by thesushilsharma** [comment]
Let me see. I am new to pg vector. 

If i reach to any positive solution i share it.

**Comment by homanp** [comment]
@yusofy Is working on this now.
