### ISSUE TITLE
separate index/class name for different datasource data (i.e: datasource name as index/class name)

### ISSUE THREAD

**Issue by kranthi419** [homanp/superagent#618]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

can we have separate index name for different datasource data (i.e: datasource name as index name). Currently all data are being inserted under single index.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@kranthi419 will see if we can resolve this somehow, although this a major change so would you be up for contributing?

**Comment by kranthi419** [comment]
@homanp sure, i'm up for contributing. what's your plan for achieving this.

**Comment by homanp** [comment]
> @homanp sure, i'm up for contributing. what's your plan for achieving this.

We can set an option in the vectorize_datasource method to create a new index for each datasource instead of adding to an existing one. I think that would work. 

The search in the vector db would need to adhere to this and the index should probably have a corresponding mapping id in our database as well. So we know which datasource belongs to which index.
